### ISSUE TITLE
Not recognising Mifare Classic

### ISSUE THREAD

**Issue by jpuriol** [entur/android-nfc-lib#32]
I tried to use the example app from this repo with an ACS Reader (model ACR1252). And it works fine with with a Mifare Desfire, but when a use a Mifare Classic card I hear a beep but on the app only receives the "onExternalTagLost" event. Can you help me?

**Comment by skjolber** [comment]
@jpuriol Mifare Classic is not supported. But adding support is not a big job, as there is already support [here](https://github.com/skjolber/external-nfc-api/blob/master/core/src/main/java/com/github/skjolber/nfc/hce/tech/mifare/MifareClassicTagFactory.java).
