### ISSUE TITLE
Reader example can't get NDEF records

### ISSUE THREAD

**Issue by clayton-bridge** [entur/android-nfc-lib#42]
Hi there and thanks for sharing your code! I got your reader example working on my Galaxy Tab A9 but my ACR122U reader is not seeing NDEF in the tag's TechList. This is preventing me from getting the NDEF record off the card. Does your example reader code support NDEF?

Thanks again!
Clayton

**Comment by skjolber** [comment]
Hi @clayton-bridge. This project does not support NDEF.
